services:
  mongodb:
    image: mongo:8.3
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: longscrape
      GLIBC_TUNABLES: glibc.pthread.rseq=1
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-stack-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mongodb-data:
  redis-stack-data:
