[project]
name = "longscrape-workspace"
version = "0.2.2"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Franciszek Łopuszański", email = "franopusz2006@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = [
    "longscrape-core",
    "longscrape[all]",
    "longscrape-scrapy",
    "ipykernel>=7.3.0",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pandas-stubs>=3.0.5.260730",
    "pre-commit>=4.6.2",
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "ruff>=0.16.3",
    "patchright>=1.61.2",
    "playwright>=1.62.0",
    "scrapy>=2.17.0",
    "pyrefly>=1.2.0",
    "structlog>=26.1.0",
]

[tool.uv.workspace]
members = [
    "packages/longscrape_core",
    "packages/longscrape",
    "packages/longscrape_scrapy",
]

[tool.uv.sources]
longscrape-core = { workspace = true }
longscrape = { workspace = true }
longscrape-scrapy = { workspace = true }

[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "basic"
include = [
    "packages",
    "examples",
    "playbooks",
]
exclude = [
    "**/node_modules",
    "**/__pycache__",
    "**/build",
    "**/dist",
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
]
extend-select = ["I"]
