from typing import Protocol
from uuid import UUID

from longscrape.worker.context import JobSubmitter
from longscrape.worker.models import Job, StoredJob


class JobQueue(JobSubmitter, Protocol):
    async def get(
        self, kind: str | None = None, *, worker_id: str | None = None
    ) -> Job: ...
    def empty(
        self, kind: str | None = None, *, worker_id: str | None = None
    ) -> bool: ...


class JobStore(Protocol):
    async def register(self, job: Job, *, key: str | None = None) -> bool: ...
    async def get(self, job_id: UUID) -> StoredJob: ...
    async def start(self, job_id: UUID) -> None: ...
    async def succeed(self, job_id: UUID) -> None: ...
    async def fail(self, job_id: UUID, error: Exception) -> None: ...
