"""Public domain types and pipeline contracts for longscrape."""

from longscrape_core._json import (
    FrozenJsonObject,
    JsonInput,
    JsonObject,
    JsonScalar,
    JsonValue,
)
from longscrape_core.context import ContextKey, PipelineContext, WorkController
from longscrape_core.failures import (
    HttpStatusError,
    PipelineFailure,
    PipelineStage,
    Recovery,
    RecoveryAction,
    StageExecutionError,
)
from longscrape_core.models import (
    Document,
    DocumentInput,
    DocumentRef,
    InputQuery,
    InputUrl,
    Job,
    JobEvent,
    JobEventType,
    JobInput,
    JobLease,
    JobSpec,
    JobState,
    JobView,
    Record,
    RecordRef,
)
from longscrape_core.observability import (
    StageObserver,
    observe_extractor,
    observe_fetcher,
    observe_stage,
    observe_transformer,
)
from longscrape_core.protocols import (
    DocumentArchive,
    DocumentCache,
    Extractor,
    Fetcher,
    JobExecutor,
    RecordMerger,
    RecordSink,
    RecordStore,
    RecoveryPolicy,
    Sink,
    Transformer,
    WorkStore,
)

__all__ = [
    "ContextKey",
    "Document",
    "DocumentArchive",
    "DocumentCache",
    "DocumentInput",
    "DocumentRef",
    "Extractor",
    "Fetcher",
    "FrozenJsonObject",
    "HttpStatusError",
    "InputQuery",
    "InputUrl",
    "Job",
    "JobEvent",
    "JobEventType",
    "JobExecutor",
    "JobInput",
    "JobLease",
    "JobSpec",
    "JobState",
    "JobView",
    "JsonObject",
    "JsonInput",
    "JsonScalar",
    "JsonValue",
    "PipelineContext",
    "PipelineFailure",
    "PipelineStage",
    "Record",
    "RecordMerger",
    "RecordRef",
    "RecordSink",
    "RecordStore",
    "Recovery",
    "RecoveryAction",
    "RecoveryPolicy",
    "Sink",
    "StageExecutionError",
    "StageObserver",
    "Transformer",
    "WorkController",
    "WorkStore",
    "observe_extractor",
    "observe_fetcher",
    "observe_stage",
    "observe_transformer",
]
