from typing import Any, Protocol


class BrowserMiddleware(Protocol):
    """Handle a Playwright-compatible route."""

    async def handle(self, route: Any) -> bool: ...


class BrowserManagerProtocol(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def create_page(self) -> Any: ...
    def register_middleware(self, middleware: BrowserMiddleware) -> None: ...
