from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from playwright.async_api import Page, Route


class PlaywrightMiddleware(Protocol):
    async def handle(self, route: "Route") -> bool: ...


class PlaywrightManager(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def create_page(self) -> "Page": ...
    def register_middleware(self, middleware: PlaywrightMiddleware) -> None: ...
